---
title: "Collaborative Research: Spatial Distribution of Crime as a Function of the Demarcation of Police Power"
author: "Sebastian Martinez - Fabian Bohnenberger"
date: "October 9, 2015"
output: html_document
bibliography:
    - crimemapping.bib
---

## Summary 

This research project aims to analyze the relation between the location of reported crimes in a city and the spatial demarcations of police power, i.e. the location and distribution of police stations and police districts accross the city. Using data on the city of Chicago (and eventually other cities), we look into crime as a function of the distance to police stations and the borders of police districts. We analyze whether certain crimes are more likely to be perpetrated at the fringes of districts and whether the average distance of certain crimes to either the police stations or district boundary has significantly changed over the last few years. Our reserach aims to show trends in the spatial distribution of crimes as a function of the intentional or unintentional demarcation of police power in the city. Our findings can inform both police forces and policy-makers in their planning and decision-making. In terms of methodology, we use R to obtain publicly available data on crime from the respective city database(s). To visualize the location data and calculate distances, we rely on the open-source Geographic Information System QGIS. R will be used to  create a regression model and visualize our findings. The whole project is available on GitHub: [CrimeMapping](https://github.com/martinezsebastian/CrimeMapping)

## Introduction 

Every community deals with the presence of crime. Criminal activity has a multitude of causes and the origins of crime have been the subject of investigation by many disciplines. The organization of law enforcement's response is a key factor in understanding the nature and extent of crime occurring in a specific area. For example, one city may be better fighting crime, because it has correctly identified hotspots and distributed its police forces accordingly. This often includes setting up additional police stations in trouble zones or adjusting police district and beat boundaries to better allocate existing forces.

This research project will aim at tracking the relation between the location of reported crimes in a city and the spatial demarcations of police power. We especially focus on the location and distribution of police stations, police beats and districts accross the city. By looking at crime as a function of the distance to police stations and district borders, we analyze whether certain crimes are more likely to be perpetrated at the fringes of districts and whether the average distance of certain crimes to either the police stations or district boundary has significantly changed over the last few years. If, for example, crime hotspots were to move towards the police stations, this could signify a drop in police performance over a certain time period. In this regard, this research also touchs upon the question of effectiveness of police work. For example, holding other things relatively constant, differences in crime levels at the district borders could indicate different levels of  cooperation between police districts in a given city. 

## Research Question / Hypotheses 

Our research aims to show the relationship between the spatial distribution of crimes and the demarcation of police power in the city. We operationalize the concept of "demarcation of police power" by measuring the distance between crime scenes and the location of the police station as well as the distance between crime scene and police beat and district border. The motivation for this research stems from the way a city is divided into districts, invisible to pedestrians, but limiting in the way police can effectively carry out their duty.   

### Research Question 

Our key research question is:
Does the position of a police station and the borders of its respective district have an influence on the way crimes are distributed in a city?

Complementary research questions are: i) Which types of crimes are committed where, in relation to the borders of the district/station? ii) Did certain crimes move away from the police station?

### Hypotheses 

The proposed research questions are connected to the following hypothesis:

**Hyptohesis 1**: The farther away from the police station, the more crimes are committed. 

**Hypothesis 2**: An overall rising number of crimes means crime moves closer to the police station. 

**Hypothesis 3**: For specific crimes, the number of criminal acts near the district borders are higher than those closer to the police station. 
    
    
    

## Literature Overview and Relevance of Research

A significant amount of the literature looks at socioeconomic conditions to explain the occurence of urban criminal violence @Blau1982

Lit on spatial characteristics on crime here
Described in a more conceptual manner, a city is not only set of objects placed one next to the other, but a set of places with specific functions designed for us, the citizens. Since the users interact with the physical space and vice versa, studying these interactions provide information to improve the efficiency of the function, as well as provide a better user experience. In this case, the structure of the city will be used to understand how it affects crime rates.\\

Connected to the research question presented above is the hypothesis that a denser, mixed used neighborhood has a smaller number of crime occurrences than a sprawled, more spread out neighborhood. Morenoff \& Sampson \citeyearpar{Morenoff:1997ux} show that crimes have a spatial component, often ignored by social researchers. They also argue that depending on the physical structure of a city, areas with high crime can spread out to neighboring areas in a process called ?spatial diffusion of crime?. Further, Rosenfeld et al. \citeyearpar{Rosenfeld:1999vv} found that when controlling for neighborhood demographic characteristics, the spatial distribution of crime is due to both the intrinsic characteristics of gang culture and the facilitating neighborhood characteristics. To pursue this approach, the concept of spatial weights matrix will be introduced. Following Leenders \citeyearpar{Leenders:2002fa} different characteristics of a neighborhood are included in a weights matrix to determine the use composition of a block, but also its relation with neighboring blocks, allowing for empirical research of diffusion effects in crime. 
@Morenoff:1997ux. 


Other research, especially criminological literature, focuses more on the operative part of crime prevention, which is closer to our research project. The "Broken Windows Theory" postulated by James Q. Wilson and George Kelling in 1982 in an influential article in the Atlantic Monthly represents an important starting point. @Wilson suggest that targeting minor disorder, e.g. vandalism, broken windows could help reduce more serious crime. The theory assumes that the landscape "communicates" to people. A broken window transmits to criminals the message that a community displays a lack of informal social control, and is therefore unable or unwilling to defend itself against a criminal invasion. In more recent literature, this theory is, however criticized for its simplicity. Acccording to @Harcourt, evidence from New York City crime data and from social experiments in five US cities would "provide no support for a simple first-order disorder-crime relationship as hypothesized by Wilson and Kelling, nor for the proposition that broken windows policing is the optimal use of scarce law enforcement resources."



## Data sources


add Sunlight foundation doc


## Methodology


### Data Collection 

API ... Chicago homepage, mention Sunlight Foundation doc. 


### QGIS

explain how to measure distances, include map 

### Regression (R)

outline control variables (see https://www.fbi.gov/about-us/cjis/ucr/hate-crime/2011/resources/variables-affecting-crime)

It will be important to control for a number of other factors that affect crime. Especially, economic and demographic factors specific to each city area must be considered. There are, however, a lot of factors that are not readily measurable or for which no data exists. According to @FBI, factors that are known to affect the volume and type of crime occurring from place to place are:

- Population density and degree of urbanization.
- Variations in composition of the population, particularly youth concentration.
- Stability of the population with respect to residents' mobility, commuting patterns, and transient factors.
- Modes of transportation and highway system.
- Economic conditions, including median income, poverty level, and job availability.
- Cultural factors and educational, recreational, and religious characteristics.
- Family conditions with respect to divorce and family cohesiveness.
- Climate.
- Effective strength of law enforcement agencies.
- Administrative and investigative emphases of law enforcement.
- Policies of other components of the criminal justice system (i.e., prosecutorial, judicial, correctional, and probational).
- Citizens' attitudes toward crime.
- Crime reporting practices of the citizenry.




## Bibliography 
