---
title: "Proposal"
author: "Sebastian Martinez - Fabian Bohnenberger"
date: "October 9, 2015"
output: html_document
bibliography:
    - crimemapping.bib
---

The research proposed in this document aims to analyze the relation between the location of reported thefts in the city of Chicago and the location of police stations and their position within the district. 
The analysis will follow @Morenoff:1997ux. 

 - Crime committed in the city as a function of the distance to the police station and to the border of the police district
 -- which crimes are committed where, in relation to the borders of the district/station
 -- Did certain crimes move away from the police station
 - include the map

Outline
- Introduction
- Literature review
- Methodology
-- QGIS
-- Distances
-- Import back into R.
-- Regression.



##Cited Works:

\section{Literature/Theoretical Approach},
Described in a more conceptual manner, a city is not only set of objects placed one next to the other, but a set of places with specific functions designed for us, the citizens. Since the users interact with the physical space and vice versa, studying these interactions provide information to improve the efficiency of the function, as well as provide a better user experience. In this case, the structure of the city will be used to understand how it affects crime rates.\\

Connected to the research question presented above is the hypothesis that a denser, mixed used neighborhood has a smaller number of crime occurrences than a sprawled, more spread out neighborhood. Morenoff \& Sampson \citeyearpar{Morenoff:1997ux} show that crimes have a spatial component, often ignored by social researchers. They also argue that depending on the physical structure of a city, areas with high crime can spread out to neighboring areas in a process called ‘spatial diffusion of crime’. Further, Rosenfeld et al. \citeyearpar{Rosenfeld:1999vv} found that when controlling for neighborhood demographic characteristics, the spatial distribution of crime is due to both the intrinsic characteristics of gang culture and the facilitating neighborhood characteristics. To pursue this approach, the concept of spatial weights matrix will be introduced. Following Leenders \citeyearpar{Leenders:2002fa} different characteristics of a neighborhood are included in a weights matrix to determine the use composition of a block, but also its relation with neighboring blocks, allowing for empirical research of diffusion effects in crime. 

